name: workflow
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
on:
  workflow_dispatch:
  push:
    branches: ['**']

jobs:
  job1:
    steps:
      - name: simulate job
        uses: docker://alpine:latest
        run: 'sleep 10'
